//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public long ChannelId { get; set; }
        public Nullable<long> ParentChannelId { get; set; }
        public string ChannelName { get; set; }
        public string ChannelEmail { get; set; }
        public string DestinationName { get; set; }
        public string DestinationIP { get; set; }
        public string DestinationUserName { get; set; }
        public string DestinationPassword { get; set; }
        public string DestinationCountry { get; set; }
        public string DestinationCity { get; set; }
        public string DestinationGroup { get; set; }
        public string SourcePath { get; set; }
        public string DestinationType { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> AccountId { get; set; }
        public string ChannelType { get; set; }
        public string DestinationFolder { get; set; }
        public string FileNomenclature { get; set; }
        public string FileFormats { get; set; }
        public string StagingPath { get; set; }
        public string ApprovedPath { get; set; }
        public string RejectedPath { get; set; }
        public Nullable<bool> ZeeWorkflow { get; set; }
    }
}
