//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelApprover
    {
        public long ChannelApproverId { get; set; }
        public Nullable<long> ChannelId { get; set; }
        public string AlternativeName { get; set; }
        public string ActualName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> ApproverOrder { get; set; }
    }
}
