//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public short CityId { get; set; }
        public Nullable<short> CountryId { get; set; }
        public string CityName { get; set; }
        public string Status { get; set; }
    }
}
