//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationVersionHistory
    {
        public long DestVerHistId { get; set; }
        public Nullable<long> DestVerId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string SourceFilePath { get; set; }
        public string DestinationFilePath { get; set; }
        public Nullable<decimal> PercentageTransferred { get; set; }
        public string DeliveryStatus { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
