//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationVersion
    {
        public long DestVerId { get; set; }
        public long AccountId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<int> DestinationId { get; set; }
        public Nullable<long> VersionId { get; set; }
        public Nullable<long> ChannelId { get; set; }
        public Nullable<long> SubChannelId { get; set; }
        public Nullable<bool> IsSwitch { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
        public string SLA { get; set; }
        public Nullable<System.DateTime> SlaStartTime { get; set; }
        public Nullable<System.DateTime> SlaEndTime { get; set; }
        public string DeliverStatus { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> DeliveryStartTime { get; set; }
        public Nullable<System.DateTime> DeliveryEndTime { get; set; }
        public string SourceFilePath { get; set; }
        public string DestinationFilePath { get; set; }
        public Nullable<decimal> PercentageTransferred { get; set; }
        public Nullable<int> TryCount { get; set; }
        public string StagingFilePath { get; set; }
        public string StagingFileName { get; set; }
        public string StagingDeliveryStatus { get; set; }
        public string StagingErrorMessage { get; set; }
        public Nullable<System.DateTime> StagingDeliveryStartTime { get; set; }
        public Nullable<System.DateTime> StagingDeliveryEndTime { get; set; }
        public Nullable<decimal> StagingPercentageTransferred { get; set; }
        public Nullable<int> StagingTryCount { get; set; }
        public Nullable<int> NoOfApprovalsDone { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<System.DateTime> ApprovalDateTime { get; set; }
        public string HouseId { get; set; }
        public string ApprovedStatus { get; set; }
        public Nullable<System.DateTime> ApprovedStartTime { get; set; }
        public Nullable<System.DateTime> ApprovedEndTime { get; set; }
        public Nullable<int> ApprovedTryCount { get; set; }
        public string ApprovedDestinationPath { get; set; }
        public string ApprovedDestinationFile { get; set; }
        public string ApprovedErrorMessage { get; set; }
        public string RejectedStatus { get; set; }
        public Nullable<System.DateTime> RejectedStartTime { get; set; }
        public Nullable<System.DateTime> RejectedEndTime { get; set; }
        public Nullable<int> RejectedTryCount { get; set; }
        public string RejectedDestinationPath { get; set; }
        public string RejectedDestinationFile { get; set; }
        public string RejectedErrorMessage { get; set; }
    }
}
