//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int ExceptionID { get; set; }
        public string ExceptionFun { get; set; }
        public Nullable<int> ExceptionErrID { get; set; }
        public string ExceptionMsg { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string XML_data { get; set; }
    }
}
