//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceExpenseTemplate
    {
        public byte InvExpId { get; set; }
        public string TemplateType { get; set; }
        public string TemplateDefault { get; set; }
        public string TemplateHtml { get; set; }
        public string TemaplateEmailSubj { get; set; }
        public string TemplateEmail { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
    }
}
