//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceEmail
    {
        public long InvEmailId { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public string EmailSubject { get; set; }
        public string EmailContent { get; set; }
        public string EmailToAddress { get; set; }
        public string EmailAttachment { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
    }
}
