//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public long InvoiceId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string PrimaryContactPerson { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone1 { get; set; }
        public string InvAddress1 { get; set; }
        public string InvAddress2 { get; set; }
        public string InvCity { get; set; }
        public string InvState { get; set; }
        public Nullable<int> InvCountry { get; set; }
        public string InvPincode { get; set; }
        public Nullable<double> InvInitialTotal { get; set; }
        public Nullable<double> InvDiscountPercent { get; set; }
        public Nullable<double> InvDiscountAmt { get; set; }
        public Nullable<double> InvAdvancePayment { get; set; }
        public string InvRoundOff { get; set; }
        public Nullable<double> InvFinalTotal { get; set; }
        public Nullable<double> InvFinalBalance { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
    }
}
