//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment
    {
        public long InvPaymentId { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentType { get; set; }
        public string PaymentRefNo { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public string PaymentCurrency { get; set; }
        public Nullable<double> PaymentBalanceAmt { get; set; }
        public Nullable<double> PaymentConversionRatio { get; set; }
        public Nullable<double> PaymentAdjustmentAmount { get; set; }
        public string PaymentAdjustmentReason { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
    }
}
