//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItemDetail
    {
        public long InvoiceItemDetId { get; set; }
        public Nullable<long> InvoiveId { get; set; }
        public Nullable<long> IProductId { get; set; }
        public string IProductName { get; set; }
        public Nullable<double> IProductSellingPrice { get; set; }
        public string IProductUOM { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> ItemInitialTotal { get; set; }
        public Nullable<double> ItemDiscountPercent { get; set; }
        public Nullable<double> ItemDiscountAmt { get; set; }
        public Nullable<double> ItemTaxPercent { get; set; }
        public Nullable<double> ItemTaxOnAmt { get; set; }
        public Nullable<double> ItemFinalTotal { get; set; }
        public string ItemDesc { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
    }
}
