//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceProduct
    {
        public long IProductId { get; set; }
        public string IProductName { get; set; }
        public string IProductType { get; set; }
        public string IProductDescr { get; set; }
        public Nullable<double> IProductSellingPrice { get; set; }
        public string IProductUOM { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> CompanyId { get; set; }
    }
}
