//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeftMenu
    {
        public short LeftMenuId { get; set; }
        public string MenuName { get; set; }
        public Nullable<byte> MenuOrder { get; set; }
        public Nullable<short> ParentMenuId { get; set; }
        public string ParentMenuIcon { get; set; }
        public string MenuUrl { get; set; }
        public string MenuActionName { get; set; }
        public string MenuControllerName { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
    }
}
