//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long NotificationId { get; set; }
        public long UserGroupId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<bool> AQC_Passed { get; set; }
        public Nullable<bool> Order_Committed { get; set; }
        public Nullable<bool> To_Destination { get; set; }
        public Nullable<bool> Ver_ToAll { get; set; }
        public Nullable<bool> All_To_All { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> AccountId { get; set; }
    }
}
