//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public long ProjectId { get; set; }
        public long AccountId { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectName { get; set; }
        public long ClientId { get; set; }
        public long BrandId { get; set; }
        public long AgencyId { get; set; }
        public long MediaId { get; set; }
        public long ProductionId { get; set; }
        public long PostId { get; set; }
        public long AudioId { get; set; }
        public Nullable<long> AdvertiserGroupId { get; set; }
        public Nullable<long> SectorId { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
        public string ApproverStatus { get; set; }
    }
}
