//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMenu
    {
        public byte MenuId { get; set; }
        public string MenuName { get; set; }
        public string MenuTabId { get; set; }
        public string MenuTabName { get; set; }
        public string Status { get; set; }
    }
}
