//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectVersionApproval
    {
        public long ProjectVerApprId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> VersionId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string ApprovalStatus { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
        public string HouseId { get; set; }
        public Nullable<long> ChannelApproverId { get; set; }
    }
}
