//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupMenu
    {
        public int UGroupMenuId { get; set; }
        public short UserGroupId { get; set; }
        public byte MenuId { get; set; }
        public string Access { get; set; }
        public string Status { get; set; }
    }
}
