//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public long UserAccId { get; set; }
        public Nullable<long> UserId { get; set; }
        public long AccountId { get; set; }
        public short GroupId { get; set; }
        public string ProjectFlag { get; set; }
        public string ProjectFlagName { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
    }
}
