//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSendItDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupLeftMenu
    {
        public int UserGroupLeftMenuId { get; set; }
        public Nullable<short> UserGroupId { get; set; }
        public Nullable<short> LeftMenuId { get; set; }
        public string Access { get; set; }
    }
}
